### ISSUE TITLE
0.11.18 startup crash

### ISSUE THREAD

**Issue by ghost** [Kikkers/Factorio_Smart-Circuit-Systems#1]
I'm getting the following startup error with Factorio 0.11.18:

omni-actuator has wrong pickup vector as it isn't in safe distance from the tile edge.

**Comment by Kikkers** [comment]
Hi, thanks for showing interest, but I'm not actively supporting this mod right now. I might make a patch once we have a new stable version (no promises though). In the meantime, see the forum thread if anyone else had this problem, they might have fixed it by themselves.

**Comment by Kikkers** [comment]
I've uploaded a few fixes that were added in an unofficial patch (and added the proper credits). Hopefully this is an adequate fix, so I'll close this issue.
